Added check for valid test or module name, so user is not left with mysterious error of:
File "/home/fhantho/pupympireloaded/pupympi/benchmark/pupymark.py", line 267, in testrunner
    header += "# %s limit:%s processes:%i\n" % (("test:"+fixed_test if fixed_test is not None else "module:"+fixed_module),nicelimit,ci.w_num_procs)
TypeError: %d format: a number is required, not NoneType

when spelling eg. "Reduce" as "reduce"